apiVersion: apps/v1
kind: Deployment
metadata:
  name: barbearia-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: barbearia-pod
  template:
    metadata: 
      labels:
        name: barbearia-pod
    spec:
      containers:
      - name: barbearia-pod
        image: aluracursos/sistema-noticias:1
        resources:
          requests:
            cpu: 100m
        ports:
          - containerPort: 80
        env:
          - name: "HOST_DB"
            value: "barbearia-service:3306"
          - name: "USER_DB"
            value: "root"
          - name: "PASS_DB"
            value: "q1w2e3r4"
          - name: "DATABASE_DB"
            value: "empresa"
