apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: barbearia-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: barbearia-deployment
  minReplicas: 2
  maxReplicas: 40
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
    
